### ISSUE TITLE
Not able to run PHP app

### ISSUE THREAD

**Issue by saurabhagrawal0412** [airavata-courses/stephenpaul2727#3]
Hi @stephenpaul2727 ,
Looks like the paths are Linux specific.
``
G:\SGAReview\stephenpaul2727\Assignment1\TimeTeller>php artisan key:generate
PHP Warning:  require(G:\SGAReview\stephenpaul2727\Assignment1\TimeTeller\bootst
rap/../vendor/autoload.php): failed to open stream: No such file or directory in
 G:\SGAReview\stephenpaul2727\Assignment1\TimeTeller\bootstrap\autoload.php on l
ine 17
PHP Fatal error:  require(): Failed opening required 'G:\SGAReview\stephenpaul27
27\Assignment1\TimeTeller\bootstrap/../vendor/autoload.php' (include_path='.;C:\
php\pear') in G:\SGAReview\stephenpaul2727\Assignment1\TimeTeller\bootstrap\auto
load.php on line 17
``
Please help to run this on Windows:.

Thanks

**Comment by stephenpaul2727** [comment]
I figured out the issue. Laravel requires the project to be inside the a local server directory. So try installing xampp and paste the timeteller project( Download again from github source code because local file you have already has dependencies satisfied.) inside xampp htdocs folder. Then run the three commands again. I tested it in a windows machine and it works fine. Let me know if you face any other problems. Thanks for pointing out the issue.

**Comment by stephenpaul2727** [comment]
Also, While installing composer, point to the php.exe inside xampp.

thanks

**Comment by saurabhagrawal0412** [comment]
Hi @stephenpaul2727 ,
Thanks for providing resolution for starting the PHP app.
All the apps are working fine now.
Attaching the screenshot.

![image](https://user-images.githubusercontent.com/19391379/29999816-0cef4d28-9024-11e7-9e2f-6b1110761c16.png)
