### ISSUE TITLE
Unclear installation steps for composer and php

### ISSUE THREAD

**Issue by madrinathapa** [airavata-courses/stephenpaul2727#8]
Can you please provide a step-by-step procedure for installing and running the PHP service(with the urls).

**Comment by stephenpaul2727** [comment]
Hi Madrina,

I provided the detailed description in Running Laravel  App (Windows Users). If that's not enough to get you started. Please let me know, I will update the readme with more information regarding installation process. 

Thanks

**Comment by madrinathapa** [comment]
Hi Stephen,

I had to execute this command to start the timeteller service -> php composer.phar install
It might be because of the steps I followed while installing Composer but I thought I should let you know. Also, I don't see any information regarding starting API Server on your readme. Could you please update that too?

Thank you,
Madrina Thapa

**Comment by stephenpaul2727** [comment]
Hi Madrina,

Yes, that's true, I'm sorry to not mention that. You have now installed PHP through XAMPP. So it's not installed globally. So that's why composer is not a command. I will update the readme with this enhancement. thanks for notifying. Coming to API Server, it needs rabbitmq implementation. I will update readme after this is done.

**Comment by stephenpaul2727** [comment]
I'm closing this issue for now. If you face anything while installation. You are welcome to re-open this issue.
